seed: 123
data:
    directory: "/home/app/src/data/car_ims_v2/train"
    labels: "inferred"
    label_mode: "categorical"
    validation_split: 0.2
    image_size: [224, 224]
    batch_size:  32
    shuffle: True


model:
    weights: "imagenet"
    input_shape: [224, 224, 3]
    classes: 196
    dropout_rate: 0.35 
    data_aug_layer:
        random_flip:
            mode: "horizontal"
        random_rotation:
            factor: 0.1
        random_zoom:
            height_factor: 0.2
            width_factor: 0.2
        random_contrast:
            factor: [0.2, 0.5]

compile:
    optimizer:
        sgd: 
            learning_rate: 0.0005
            momentum: 0.98
    loss: "categorical_crossentropy"
    metrics: ["accuracy"]

fit:
    epochs: 13
    callbacks:
        model_checkpoint:
            filepath: "/home/app/src/experiments/finetun11/model.{epoch:02d}-{val_loss:.4f}.h5"
            save_best_only: True
            save_weights_only: True
        tensor_board:
            log_dir: "/home/app/src/experiments/finetun11/logs"
        early_stopping:
            monitor: 'val_loss'
            patience: 3
            mode: 'min'
            restore_best_weights: True