seed: 123
data:
    directory: "/home/app/src/data/car_ims_v2/train"
    labels: "inferred"
    shuffle: True
    label_mode: "categorical"
    validation_split: 0.2
    image_size: [224, 224]
    batch_size: 64

model:
    weights: "imagenet"
    input_shape: [224, 224, 3]
    classes: 196
    dropout_rate: 0.4
    data_aug_layer:
        random_flip:
            mode: "horizontal"
        random_rotation:
            factor: 0.05
        random_zoom:
            height_factor: 0.2
            width_factor: 0.2
        random_contrast:
            factor: [0.2, 0.5]

compile:
    optimizer:
        adam:
            learning_rate: 0.01
            epsilon: 0.05 # 0.05
    loss: "categorical_crossentropy"
    metrics: ["accuracy"]

fit:
    epochs: 8
    callbacks:
        model_checkpoint:
            filepath: "/home/app/src/experiments/warmup/model.{epoch:02d}-{val_loss:.4f}.h5"
            save_best_only: true
        tensor_board:
            log_dir: "/home/app/src/experiments/warmup/logs"
        reduce_lr_plat:
            monitor: "val_loss"
            factor: 0.3
            patience: 1 # 5
            min_lr: 0.000001
            mode: "auto"
            cooldown: 0
            min_delta: 0.5 # 0.05